"""Initial Schema

Revision ID: 4ca619e35159
Revises:
Create Date: 2026-02-16 18:57:24.634523

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ca619e35159"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.AutoString(), nullable=True),
        sa.Column("iso_code", sqlmodel.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "labor_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.AutoString(), nullable=True),
        sa.Column("hourly_rate", sa.Float(), nullable=False),
        sa.Column("skill_level", sqlmodel.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operation_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.AutoString(), nullable=True),
        sa.Column("op_type", sa.Enum("STANDARD", "PURCHASE", name="optype"), nullable=False),
        sa.Column("instructions", sqlmodel.AutoString(), nullable=True),
        sa.Column("setup_time_minutes", sa.Float(), nullable=False),
        sa.Column("estimated_duration_minutes", sa.Float(), nullable=False),
        sa.Column("yield_rate", sa.Float(), nullable=False),
        sa.Column("cost_estimate", sa.Float(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "part_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.AutoString(), nullable=True),
        sa.Column("unit_of_measure", sqlmodel.AutoString(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_type", sqlmodel.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operation_input_currency",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("currency_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit", sqlmodel.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["currency_id"], ["currency_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["operation_id"], ["operation_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("operation_id", "currency_id"),
    )
    op.create_table(
        "operation_input_labor",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("labor_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit", sqlmodel.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["labor_id"], ["labor_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["operation_id"], ["operation_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("operation_id", "labor_id"),
    )
    op.create_table(
        "operation_input_parts",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("part_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit", sqlmodel.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["operation_id"], ["operation_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["part_id"], ["part_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("operation_id", "part_id"),
    )
    op.create_table(
        "tool_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.AutoString(), nullable=True),
        sa.Column("linked_part_id", sa.Uuid(), nullable=False),
        sa.Column("cost_rate", sa.Float(), nullable=False),
        sa.Column("rate_unit", sqlmodel.AutoString(), nullable=False),
        sa.Column("setup_time_minutes", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["linked_part_id"],
            ["part_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operation_input_tools",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("tool_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("unit", sqlmodel.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["operation_id"], ["operation_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tool_id"], ["tool_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("operation_id", "tool_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operation_input_tools")
    op.drop_table("tool_nodes")
    op.drop_table("operation_input_parts")
    op.drop_table("operation_input_labor")
    op.drop_table("operation_input_currency")
    op.drop_table("part_nodes")
    op.drop_table("operation_nodes")
    op.drop_table("labor_nodes")
    op.drop_table("currency_nodes")
    # ### end Alembic commands ###
